"""generations.project_id nullable

Revision ID: 23098f678327
Revises: a37deedfb22d
Create Date: 2026-10-05 02:53:55.383735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23098f678327'
down_revision: Union[str, Sequence[str], None] = 'a37deedfb22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generations', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
