"""initial schema

Revision ID: a37deedfb22d
Revises:
Create Date: 2026-09-30 19:39:17.186867

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a37deedfb22d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Entity-resolution clustering and glossary lookup need pgvector.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entries',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('intent_plain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('technical_text', sa.Text(), nullable=False),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('avoid_when', sa.Text(), nullable=True),
    sa.Column('pairs_with', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_notes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_note', sa.Text(), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version')
    )
    op.create_index(op.f('ix_glossary_entries_category'), 'glossary_entries', ['category'], unique=False)
    op.create_index(op.f('ix_glossary_entries_slug'), 'glossary_entries', ['slug'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rules',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('visible_proof', sa.Text(), nullable=True),
    sa.Column('failure_sentence', sa.Text(), nullable=True),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version')
    )
    op.create_index(op.f('ix_rules_slug'), 'rules', ['slug'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('external-reference', 'in-house', name='skillsource', native_enum=False, length=48), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_index(op.f('ix_skills_active'), 'skills', ['active'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'producer', 'reviewer', 'client', name='role', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('format', sa.Enum('micro_drama', 'feature', 'short', 'other', name='projectformat', native_enum=False, length=48), nullable=False),
    sa.Column('aspect_delivery', sa.String(length=16), nullable=False),
    sa.Column('episodes_target', sa.Integer(), nullable=True),
    sa.Column('runtime_target_s', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=80), nullable=True),
    sa.Column('model_tier', sa.String(length=40), nullable=False),
    sa.Column('candidates_per_asset', sa.Integer(), nullable=False),
    sa.Column('attempt_budget', sa.Integer(), nullable=False),
    sa.Column('keyframe_gate_audience', sa.String(length=16), nullable=False),
    sa.Column('client_approves_story', sa.Boolean(), nullable=False),
    sa.Column('budget_ceiling_usd', sa.Double(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'delivered', 'archived', name='projectstatus', native_enum=False, length=48), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('master', 'variant', 'view', 'plate', 'sheet', name='assetkind', native_enum=False, length=48), nullable=False),
    sa.Column('plate_type', sa.Enum('geography_master', 'coverage_plate', 'reverse', 'background', 'view', name='platetype', native_enum=False, length=48), nullable=True),
    sa.Column('variant_label', sa.String(length=200), nullable=True),
    sa.Column('time_of_day', sa.Enum('DAY', 'NIGHT', 'MORNING', 'EVENING', 'DAWN', 'DUSK', 'CONTINUOUS', 'UNSPECIFIED', name='timeofday', native_enum=False, length=48), nullable=True),
    sa.Column('story_days', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scenes_mark', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_asset_id', sa.Uuid(), nullable=True),
    sa.Column('tag', sa.String(length=200), nullable=False),
    sa.Column('descriptor_text', sa.Text(), nullable=True),
    sa.Column('aspect', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('plot_critical_note', sa.Text(), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('stale_reason', sa.Text(), nullable=True),
    sa.Column('approved_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag')
    )
    op.create_index(op.f('ix_assets_entity_id'), 'assets', ['entity_id'], unique=False)
    op.create_index(op.f('ix_assets_entity_type'), 'assets', ['entity_type'], unique=False)
    op.create_index(op.f('ix_assets_parent_asset_id'), 'assets', ['parent_asset_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_project_id'), 'audit_log', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_table('characters',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.Enum('lead', 'supporting', 'ensemble', 'featured', 'bit', name='charactertier', native_enum=False, length=48), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('speaks', sa.Boolean(), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acting_profile', sa.Text(), nullable=True),
    sa.Column('voice_block', sa.Text(), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_project_id'), 'comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_comments_target_id'), 'comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_comments_target_type'), 'comments', ['target_type'], unique=False)
    op.create_table('entity_surfaces',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('surface_text', sa.Text(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('proposed_entity_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_entity_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'entity_type', 'surface_text')
    )
    op.create_index(op.f('ix_entity_surfaces_entity_type'), 'entity_surfaces', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_surfaces_project_id'), 'entity_surfaces', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_surfaces_proposed_entity_id'), 'entity_surfaces', ['proposed_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_surfaces_resolved_entity_id'), 'entity_surfaces', ['resolved_entity_id'], unique=False)
    op.create_table('episodes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('logline', sa.Text(), nullable=True),
    sa.Column('runtime_target_s', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number')
    )
    op.create_index(op.f('ix_episodes_project_id'), 'episodes', ['project_id'], unique=False)
    op.create_table('generations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('prompt_sections_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_asset_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_versions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_job_id', sa.String(length=200), nullable=True),
    sa.Column('raw_request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'submitted', 'running', 'succeeded', 'failed', 'cancelled', name='generationstatus', native_enum=False, length=48), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_kind', sa.Enum('agent', 'user', name='actorkind', native_enum=False, length=48), nullable=False),
    sa.Column('created_by_agent', sa.String(length=80), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_project_id'), 'generations', ['project_id'], unique=False)
    op.create_index(op.f('ix_generations_provider_job_id'), 'generations', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_generations_target_id'), 'generations', ['target_id'], unique=False)
    op.create_index(op.f('ix_generations_target_type'), 'generations', ['target_type'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'claimed', 'running', 'succeeded', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=48), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('claimed_by', sa.String(length=120), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['status', 'run_after', 'priority'], unique=False)
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('locations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_locations_project_id'), 'locations', ['project_id'], unique=False)
    op.create_table('merge_questions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merge_questions_project_id'), 'merge_questions', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'producer', 'reviewer', 'client', name='role', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_skill_pins',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=80), nullable=False),
    sa.Column('skill_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'skill_name')
    )
    op.create_index(op.f('ix_project_skill_pins_project_id'), 'project_skill_pins', ['project_id'], unique=False)
    op.create_table('props',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('prop', 'vehicle', 'vehicle_interior', 'screen_insert', name='propkind', native_enum=False, length=48), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_props_project_id'), 'props', ['project_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('plot', 'bible', 'screenplay', 'breakdown', 'reference', name='sourcekind', native_enum=False, length=48), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_documents_project_id'), 'source_documents', ['project_id'], unique=False)
    op.create_table('worlds',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('palette_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_prefix', sa.Text(), nullable=True),
    sa.Column('era_rules', sa.Text(), nullable=True),
    sa.Column('finish_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_worlds_project_id'), 'worlds', ['project_id'], unique=False)
    op.create_table('asset_versions',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('images_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('descriptor_text', sa.Text(), nullable=True),
    sa.Column('chosen_generation_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version')
    )
    op.create_index(op.f('ix_asset_versions_asset_id'), 'asset_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_versions_chosen_generation_id'), 'asset_versions', ['chosen_generation_id'], unique=False)
    op.create_table('continuity',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('story_day', sa.String(length=16), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('costume_asset_id', sa.Uuid(), nullable=True),
    sa.Column('costume_label', sa.String(length=200), nullable=True),
    sa.Column('hair', sa.Text(), nullable=True),
    sa.Column('state_notes', sa.Text(), nullable=True),
    sa.Column('episodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['costume_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'story_day', 'character_id')
    )
    op.create_index(op.f('ix_continuity_character_id'), 'continuity', ['character_id'], unique=False)
    op.create_index(op.f('ix_continuity_project_id'), 'continuity', ['project_id'], unique=False)
    op.create_index(op.f('ix_continuity_story_day'), 'continuity', ['story_day'], unique=False)
    op.create_table('gate_decisions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.Enum('G0', 'G1', 'G2', 'G3', 'G4', name='gate', native_enum=False, length=48), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('chosen_generation_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'changes_requested', name='gatedecisionkind', native_enum=False, length=48), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chosen_generation_id'], ['generations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_decisions_gate'), 'gate_decisions', ['gate'], unique=False)
    op.create_index(op.f('ix_gate_decisions_project_id'), 'gate_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_gate_decisions_target_id'), 'gate_decisions', ['target_id'], unique=False)
    op.create_table('location_sub_areas',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('int_ext', sa.Enum('INT', 'EXT', 'INT/EXT', name='intext', native_enum=False, length=48), nullable=True),
    sa.Column('times_of_day', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scene_count', sa.Integer(), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=True),
    sa.Column('continuity_risk', sa.Text(), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'name')
    )
    op.create_index(op.f('ix_location_sub_areas_location_id'), 'location_sub_areas', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_sub_areas_project_id'), 'location_sub_areas', ['project_id'], unique=False)
    op.create_index(op.f('ix_location_sub_areas_world_id'), 'location_sub_areas', ['world_id'], unique=False)
    op.create_table('prompt_patches',
    sa.Column('generation_from_id', sa.Uuid(), nullable=False),
    sa.Column('generation_to_id', sa.Uuid(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('prompt_ambiguity', 'prompt_contradiction', 'model_limitation', 'asset_weakness', 'reference_error', 'rule_violation', name='failurecategory', native_enum=False, length=48), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_from_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generation_to_id'], ['generations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_patches_generation_from_id'), 'prompt_patches', ['generation_from_id'], unique=False)
    op.create_index(op.f('ix_prompt_patches_generation_to_id'), 'prompt_patches', ['generation_to_id'], unique=False)
    op.create_table('reviews',
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_kind', sa.Enum('agent', 'user', name='actorkind', native_enum=False, length=48), nullable=False),
    sa.Column('reviewer_agent', sa.String(length=80), nullable=True),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('verdict', sa.Enum('pass', 'fail', 'override_pass', 'override_fail', name='reviewverdict', native_enum=False, length=48), nullable=False),
    sa.Column('category', sa.Enum('prompt_ambiguity', 'prompt_contradiction', 'model_limitation', 'asset_weakness', 'reference_error', 'rule_violation', name='failurecategory', native_enum=False, length=48), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposed_fix', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_generation_id'), 'reviews', ['generation_id'], unique=False)
    op.create_table('scenes',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('number_label', sa.String(length=24), nullable=True),
    sa.Column('intercut_group', sa.String(length=40), nullable=True),
    sa.Column('int_ext', sa.Enum('INT', 'EXT', 'INT/EXT', name='intext', native_enum=False, length=48), nullable=True),
    sa.Column('time_of_day', sa.Enum('DAY', 'NIGHT', 'MORNING', 'EVENING', 'DAWN', 'DUSK', 'CONTINUOUS', 'UNSPECIFIED', name='timeofday', native_enum=False, length=48), nullable=False),
    sa.Column('story_day', sa.String(length=16), nullable=True),
    sa.Column('story_day_hint', sa.Text(), nullable=True),
    sa.Column('story_day_confirmed', sa.Boolean(), nullable=False),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('sub_area_raw', sa.Text(), nullable=True),
    sa.Column('location_sub_area_id', sa.Uuid(), nullable=True),
    sa.Column('heading_raw', sa.Text(), nullable=True),
    sa.Column('action_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('emotional_beat', sa.Text(), nullable=True),
    sa.Column('transition_out', sa.String(length=40), nullable=True),
    sa.Column('source_span', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('breakdown_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_sub_area_id'], ['location_sub_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_episode_id'), 'scenes', ['episode_id'], unique=False)
    op.create_index(op.f('ix_scenes_intercut_group'), 'scenes', ['intercut_group'], unique=False)
    op.create_index(op.f('ix_scenes_location_sub_area_id'), 'scenes', ['location_sub_area_id'], unique=False)
    op.create_index(op.f('ix_scenes_story_day'), 'scenes', ['story_day'], unique=False)
    op.create_table('dialogue_lines',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('speaker_raw', sa.Text(), nullable=False),
    sa.Column('speaker_character_id', sa.Uuid(), nullable=True),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('delivery_action', sa.Text(), nullable=True),
    sa.Column('delivery_emotion', sa.Text(), nullable=True),
    sa.Column('delivery_raw', sa.Text(), nullable=True),
    sa.Column('source_span', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_lines_scene_id'), 'dialogue_lines', ['scene_id'], unique=False)
    op.create_index(op.f('ix_dialogue_lines_speaker_character_id'), 'dialogue_lines', ['speaker_character_id'], unique=False)
    op.create_table('scene_characters',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('speaks', sa.Boolean(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'character_id')
    )
    op.create_index(op.f('ix_scene_characters_character_id'), 'scene_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_scene_characters_scene_id'), 'scene_characters', ['scene_id'], unique=False)
    op.create_table('scene_mentions',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=True),
    sa.Column('speaks', sa.Boolean(), nullable=False),
    sa.Column('resolved_entity_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_mentions_entity_type'), 'scene_mentions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_scene_mentions_resolved_entity_id'), 'scene_mentions', ['resolved_entity_id'], unique=False)
    op.create_index(op.f('ix_scene_mentions_scene_id'), 'scene_mentions', ['scene_id'], unique=False)
    op.create_table('shots',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('letter', sa.String(length=8), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('complexity', sa.Enum('simple', 'medium', 'complex', name='complexity', native_enum=False, length=48), nullable=True),
    sa.Column('shot_card_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spatial_map', sa.Text(), nullable=True),
    sa.Column('is_master_wide', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'prompting', 'generating', 'agent_review', 'awaiting_gate', 'approved', 'rejected', 'escalated', 'stale', name='elementstatus', native_enum=False, length=48), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'letter')
    )
    op.create_index(op.f('ix_shots_scene_id'), 'shots', ['scene_id'], unique=False)
    op.create_table('shot_asset_refs',
    sa.Column('shot_id', sa.Uuid(), nullable=False),
    sa.Column('asset_version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shot_id', 'asset_version_id')
    )
    op.create_index(op.f('ix_shot_asset_refs_asset_version_id'), 'shot_asset_refs', ['asset_version_id'], unique=False)
    op.create_index(op.f('ix_shot_asset_refs_shot_id'), 'shot_asset_refs', ['shot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shot_asset_refs_shot_id'), table_name='shot_asset_refs')
    op.drop_index(op.f('ix_shot_asset_refs_asset_version_id'), table_name='shot_asset_refs')
    op.drop_table('shot_asset_refs')
    op.drop_index(op.f('ix_shots_scene_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scene_mentions_scene_id'), table_name='scene_mentions')
    op.drop_index(op.f('ix_scene_mentions_resolved_entity_id'), table_name='scene_mentions')
    op.drop_index(op.f('ix_scene_mentions_entity_type'), table_name='scene_mentions')
    op.drop_table('scene_mentions')
    op.drop_index(op.f('ix_scene_characters_scene_id'), table_name='scene_characters')
    op.drop_index(op.f('ix_scene_characters_character_id'), table_name='scene_characters')
    op.drop_table('scene_characters')
    op.drop_index(op.f('ix_dialogue_lines_speaker_character_id'), table_name='dialogue_lines')
    op.drop_index(op.f('ix_dialogue_lines_scene_id'), table_name='dialogue_lines')
    op.drop_table('dialogue_lines')
    op.drop_index(op.f('ix_scenes_story_day'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_location_sub_area_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_intercut_group'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_episode_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_reviews_generation_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_prompt_patches_generation_to_id'), table_name='prompt_patches')
    op.drop_index(op.f('ix_prompt_patches_generation_from_id'), table_name='prompt_patches')
    op.drop_table('prompt_patches')
    op.drop_index(op.f('ix_location_sub_areas_world_id'), table_name='location_sub_areas')
    op.drop_index(op.f('ix_location_sub_areas_project_id'), table_name='location_sub_areas')
    op.drop_index(op.f('ix_location_sub_areas_location_id'), table_name='location_sub_areas')
    op.drop_table('location_sub_areas')
    op.drop_index(op.f('ix_gate_decisions_target_id'), table_name='gate_decisions')
    op.drop_index(op.f('ix_gate_decisions_project_id'), table_name='gate_decisions')
    op.drop_index(op.f('ix_gate_decisions_gate'), table_name='gate_decisions')
    op.drop_table('gate_decisions')
    op.drop_index(op.f('ix_continuity_story_day'), table_name='continuity')
    op.drop_index(op.f('ix_continuity_project_id'), table_name='continuity')
    op.drop_index(op.f('ix_continuity_character_id'), table_name='continuity')
    op.drop_table('continuity')
    op.drop_index(op.f('ix_asset_versions_chosen_generation_id'), table_name='asset_versions')
    op.drop_index(op.f('ix_asset_versions_asset_id'), table_name='asset_versions')
    op.drop_table('asset_versions')
    op.drop_index(op.f('ix_worlds_project_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_source_documents_project_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_props_project_id'), table_name='props')
    op.drop_table('props')
    op.drop_index(op.f('ix_project_skill_pins_project_id'), table_name='project_skill_pins')
    op.drop_table('project_skill_pins')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_merge_questions_project_id'), table_name='merge_questions')
    op.drop_table('merge_questions')
    op.drop_index(op.f('ix_locations_project_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_generations_target_type'), table_name='generations')
    op.drop_index(op.f('ix_generations_target_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_provider_job_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_project_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_episodes_project_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_entity_surfaces_resolved_entity_id'), table_name='entity_surfaces')
    op.drop_index(op.f('ix_entity_surfaces_proposed_entity_id'), table_name='entity_surfaces')
    op.drop_index(op.f('ix_entity_surfaces_project_id'), table_name='entity_surfaces')
    op.drop_index(op.f('ix_entity_surfaces_entity_type'), table_name='entity_surfaces')
    op.drop_table('entity_surfaces')
    op.drop_index(op.f('ix_comments_target_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_target_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_project_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_project_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_parent_asset_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_entity_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_entity_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_active'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_rules_slug'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_glossary_entries_slug'), table_name='glossary_entries')
    op.drop_index(op.f('ix_glossary_entries_category'), table_name='glossary_entries')
    op.drop_table('glossary_entries')
    # ### end Alembic commands ###
